config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/dashboard'
  get 'posts/create'
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :image_url, presence: true
    validates :content, presence: true
    before_save :censurate

    def censurate
        self.content = self.content.gsub("", "")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: 'desafiovamoscontodo', password: 'XAHTJEAS23123%23', only: :dashboard

  def index
    @post= Post.all.order(created_at: :desc)
  end

  def dashboard
    @post= Post.new
  end

  def create
    @post= Post.create(title: params[:title], image_url: params[:image_url], content: params[:content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container"><%= yield %></div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/posts/create.html.erb
<div class="container mt-5">
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2 class="text-danger font-weight-bold">
      <%= pluralize(@post.errors.count, "error") %> prohibited this post from
      being saved:
    </h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li class="font-weight-bold text-danger"><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% else %>
  <h2 class="h1 text-center text-light bg-dark border border-info">
    ¡Post creado!
  </h2>
  <div class="mr-5 text-center mt-3">
    <a class="btn btn-lg btn-info" href="<%=posts_index_path%>" role="button">Go Post</a>
  </div>
  <% end %>
</div>

app/views/posts/dashboard.html.erb
<form action ='/posts/create' class="mt-3" id="create_posts">
  <div class="form-group" class="mt-5">
    <label for="title">Title</label>
    <input name="title" type="text" class="form-control bg-dark text-white font-weight-bold" id="titulo del post" placeholder="title">
  </div>
  <div class="form-group">
    <label for="image_url">URL</label>
    <input name="image_url" type="url" class="form-control bg-dark text-white font-weight-bold" id="link" placeholder="agregar url de imagen">
  </div>
  <div class="form-group">
    <label for="content">Content</label>
    <textarea class="form-control bg-dark font-weight-bold" name="content" id="content" rows="3" placeholder="agrega una descripcion"></textarea>
  </div>
  <button type="submit" class="btn btn-danger font-weight-bold">Enviar</button>
</form>

app/views/posts/index.html.erb
<h1 class="mt-3">Posts</h1>
<span class="mr-5"
    ><a class="btn btn-danger" href="<%=posts_dashboard_path%>" role="button"
      >Crea tu posts aqui</a
    ></span>
<div class="container row ml-2"></div>
    <% @post.each do |post|%>
        <div class="card-deck">
        <div class="card">
            <a><img class="card-img-top" src="<%= post.image_url%>" alt="image" /></a>
            <div class="card-body">
                <h2 class="card-title"><%= post.title %></h2>
                <p class="card-text"><%=post.content%></p>
                <p class="card-text"><%=post.created_at%></p>
            </div>
        </div>
        </div>
    <%end%>
</div>